'use server';

/**
 * @fileOverview A flow to auto-generate a video description based on video footage.
 *
 * - autoGenerateDescription - A function that handles the video description generation process.
 * - AutoGenerateDescriptionInput - The input type for the autoGenerateDescription function.
 * - AutoGenerateDescriptionOutput - The return type for the autoGenerateDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AutoGenerateDescriptionInputSchema = z.object({
  videoDataUri: z
    .string()
    .describe(
      'A snippet of video footage, as a data URI that must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.' // eslint-disable-line
    ),
});
export type AutoGenerateDescriptionInput = z.infer<
  typeof AutoGenerateDescriptionInputSchema
>;

const AutoGenerateDescriptionOutputSchema = z.object({
  description: z
    .string()
    .describe('The auto-generated description of the video.'),
});
export type AutoGenerateDescriptionOutput = z.infer<
  typeof AutoGenerateDescriptionOutputSchema
>;

export async function autoGenerateDescription(
  input: AutoGenerateDescriptionInput
): Promise<AutoGenerateDescriptionOutput> {
  return autoGenerateDescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'autoGenerateDescriptionPrompt',
  input: {schema: AutoGenerateDescriptionInputSchema},
  output: {schema: AutoGenerateDescriptionOutputSchema},
  prompt: `You are an expert video content creator specializing in writing video descriptions.

You will use this information from a snippet of video footage to create a description for the video.

Write a description of the video in 2-3 short sentences.

Video:
{{media url=videoDataUri}}`,
});

const autoGenerateDescriptionFlow = ai.defineFlow(
  {
    name: 'autoGenerateDescriptionFlow',
    inputSchema: AutoGenerateDescriptionInputSchema,
    outputSchema: AutoGenerateDescriptionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
