import type { User, Destination, Video, Story } from './types';
import data from './placeholder-images.json';

export const placeholderImages = data.placeholderImages;

export const initialUsers: User[] = [
  { id: 'u1', name: 'Alex Doe', username: 'alexdoe', avatarUrl: placeholderImages.find(p => p.id === 'avatar-1')?.imageUrl || '', bio: 'Travel enthusiast & storyteller.\nExploring the world one city at a time.', website: 'https://alexdoe.com', followers: 1258, following: 342 },
  { id: 'u2', name: 'Jane Smith', username: 'janesmith', avatarUrl: placeholderImages.find(p => p.id === 'avatar-2')?.imageUrl || '', bio: 'Mountain lover and avid hiker.\nAlways looking for the next peak to conquer.', website: 'https://janesmith.io', followers: 2345, following: 189 },
  { id: 'u3', name: 'Chris Lee', username: 'chrislee', avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxtYW4lMjBwb3J0cmFpdHxlbnwwfHx8fDE3NjgyNDIxNjB8MA&ixlib=rb-4.1.0&q=80&w=1080', bio: 'Foodie on a quest to taste the world. 🍜🌮🍕', website: 'https://chrisleeeats.com', followers: 5600, following: 89 },
  { id: 'u4', name: 'Sarah Kim', username: 'sarahkim', avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHx3b21hbiUyMHBvcnRyYWl0fGVufDB8fHx8MTc2NjUyNTk0MHww&ixlib=rb-4.1.0&q=80&w=1080', bio: 'Digital nomad and photographer. Capturing moments from around the globe.', website: 'https://sarahkim.photo', followers: 12300, following: 120 },
  { id: 'u5', name: 'Mike Johnson', username: 'mikej', avatarUrl: 'https://images.unsplash.com/photo-1557862921-37829c790f19?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxtYW58ZW58MHx8fHwxNzY4NTg1MDI3fDA&ixlib=rb-4.1.0&q=80&w=1080', bio: 'Adrenaline junkie. Surfing, skydiving, and everything in between.', website: '', followers: 875, following: 55 },
];


export const currentUser = initialUsers.find(u => u.id === 'u1')!;

export const destinations: Destination[] = [
  { id: 'd1', name: 'Goa', country: 'India', slug: 'goa', imageUrl: placeholderImages.find(p => p.id === 'dest-goa')?.imageUrl || '' },
  { id: 'd2', name: 'Manali', country: 'India', slug: 'manali', imageUrl: placeholderImages.find(p => p.id === 'dest-manali')?.imageUrl || '' },
  { id: 'd3', name: 'Paris', country: 'France', slug: 'paris', imageUrl: placeholderImages.find(p => p.id === 'dest-paris')?.imageUrl || '' },
  { id: 'd4', name: 'Kyoto', country: 'Japan', slug: 'kyoto', imageUrl: placeholderImages.find(p => p.id === 'dest-kyoto')?.imageUrl || '' },
  { id: 'd5', name: 'Bali', country: 'Indonesia', slug: 'bali', imageUrl: placeholderImages.find(p => p.id === 'dest-bali')?.imageUrl || '' },
  { id: 'd6', name: 'Rome', country: 'Italy', slug: 'rome', imageUrl: placeholderImages.find(p => p.id === 'dest-rome')?.imageUrl || '' },
  { id: 'd7', name: 'Agra', country: 'India', slug: 'agra', imageUrl: placeholderImages.find(p => p.id === 'dest-agra')?.imageUrl || '' },
  { id: 'd8', name: 'New York', country: 'USA', slug: 'new-york', imageUrl: placeholderImages.find(p => p.id === 'dest-new-york')?.imageUrl || '' },
  { id: 'd9', name: 'London', country: 'UK', slug: 'london', imageUrl: placeholderImages.find(p => p.id === 'dest-london')?.imageUrl || '' },
  { id: 'd10', name: 'Tokyo', country: 'Japan', slug: 'tokyo', imageUrl: placeholderImages.find(p => p.id === 'dest-tokyo')?.imageUrl || '' },
  { id: 'd11', name: 'Sydney', country: 'Australia', slug: 'sydney', imageUrl: placeholderImages.find(p => p.id === 'dest-sydney')?.imageUrl || '' },
  { id: 'd12', name: 'Cairo', country: 'Egypt', slug: 'cairo', imageUrl: placeholderImages.find(p => p.id === 'dest-cairo')?.imageUrl || '' },
  { id: 'd13', name: 'Rio de Janeiro', country: 'Brazil', slug: 'rio-de-janeiro', imageUrl: placeholderImages.find(p => p.id === 'dest-rio')?.imageUrl || '' },
  { id: 'd14', name: 'Dubai', country: 'UAE', slug: 'dubai', imageUrl: placeholderImages.find(p => p.id === 'dest-dubai')?.imageUrl || '' },
  { id: 'd15', name: 'Santorini', country: 'Greece', slug: 'santorini', imageUrl: placeholderImages.find(p => p.id === 'dest-santorini')?.imageUrl || '' },
  { id: 'd16', name: 'Machu Picchu', country: 'Peru', slug: 'machu-picchu', imageUrl: placeholderImages.find(p => p.id === 'dest-machu-picchu')?.imageUrl || '' },
  { id: 'd17', name: 'Bora Bora', country: 'French Polynesia', slug: 'bora-bora', imageUrl: placeholderImages.find(p => p.id === 'dest-bora-bora')?.imageUrl || '' },
  { id: 'd18', name: 'Venice', country: 'Italy', slug: 'venice', imageUrl: placeholderImages.find(p => p.id === 'dest-venice')?.imageUrl || '' },
  { id: 'd19', name: 'Serengeti', country: 'Tanzania', slug: 'serengeti', imageUrl: placeholderImages.find(p => p.id === 'dest-serengeti')?.imageUrl || '' },
  { id: 'd20', name: 'Jaipur', country: 'India', slug: 'jaipur', imageUrl: placeholderImages.find(p => p.id === 'dest-jaipur')?.imageUrl || '' },
  { id: 'd21', name: 'Amritsar', country: 'India', slug: 'amritsar', imageUrl: placeholderImages.find(p => p.id === 'dest-amritsar')?.imageUrl || '' },
  { id: 'd22', name: 'Varanasi', country: 'India', slug: 'varanasi', imageUrl: placeholderImages.find(p => p.id === 'dest-varanasi')?.imageUrl || '' },
  { id: 'd23', name: 'Seoul', country: 'South Korea', slug: 'seoul', imageUrl: placeholderImages.find(p => p.id === 'dest-seoul')?.imageUrl || '' },
  { id: 'd24', name: 'Bangkok', country: 'Thailand', slug: 'bangkok', imageUrl: placeholderImages.find(p => p.id === 'dest-bangkok')?.imageUrl || '' },
  { id: 'd25', name: 'Istanbul', country: 'Turkey', slug: 'istanbul', imageUrl: placeholderImages.find(p => p.id === 'dest-istanbul')?.imageUrl || '' },
  { id: 'd26', name: 'Prague', country: 'Czech Republic', slug: 'prague', imageUrl: placeholderImages.find(p => p.id === 'dest-prague')?.imageUrl || '' },
];

export const initialVideos: Video[] = [
  {
    id: 'v1',
    title: 'A Day at the Beach in Goa',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: placeholderImages.find(p => p.id === 'video-thumb-1')?.imageUrl || '',
    source: 'direct',
    user: initialUsers[0],
    views: 15000,
    likes: 1200,
    comments: [
        { id: 'c1', user: initialUsers[1], text: 'Looks amazing!', createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString() },
        { id: 'c2', user: initialUsers[0], text: 'It was the best trip!', createdAt: new Date(Date.now() - 1000 * 60 * 2).toISOString() },
    ],
    destination: destinations[0],
    category: 'Beach',
    description: 'Enjoying the sun, sand, and waves in beautiful Goa. A perfect getaway!',
  },
  {
    id: 'v2',
    title: 'Hiking in the Himalayas',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    thumbnailUrl: placeholderImages.find(p => p.id === 'video-thumb-2')?.imageUrl || '',
    source: 'direct',
    user: initialUsers[1],
    views: 22000,
    likes: 2500,
    comments: [],
    destination: destinations[1],
    category: 'Mountain',
    description: 'An adventurous trek through the stunning landscapes of Manali.',
  },
  {
    id: 'v3',
    title: 'Eiffel Tower Magic',
    videoUrl: 'https://www.youtube.com/watch?v=z_jw3rB_Pto', // Example YouTube link
    thumbnailUrl: placeholderImages.find(p => p.id === 'video-thumb-3')?.imageUrl || '',
    source: 'youtube',
    user: initialUsers[0],
    views: 50000,
    likes: 4500,
    comments: [],
    destination: destinations[2],
    category: 'City',
    description: 'A magical evening exploring the iconic Eiffel Tower in Paris.',
  },
  {
    id: 'v4',
    title: 'Peaceful Kyoto Temples',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    thumbnailUrl: placeholderImages.find(p => p.id === 'video-thumb-4')?.imageUrl || '',
    source: 'direct',
    user: initialUsers[1],
    views: 18000,
    likes: 1900,
    comments: [],
    destination: destinations[3],
    category: 'Religious',
    description: 'Finding tranquility among the ancient temples of Kyoto, Japan.',
  },
  {
    id: 'v5',
    title: 'Bali\'s Green Paradise',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnailUrl: placeholderImages.find(p => p.id === 'video-thumb-5')?.imageUrl || '',
    source: 'direct',
    user: initialUsers[0],
    views: 32000,
    likes: 3100,
    comments: [],
    destination: destinations[4],
    category: 'Tropical',
    description: 'Exploring the lush green rice terraces of Bali. A true paradise on Earth.',
  },
  {
    id: 'v6',
    title: 'Ancient Rome Revealed',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnAnAdventure.mp4',
    thumbnailUrl: placeholderImages.find(p => p.id === 'video-thumb-6')?.imageUrl || '',
    source: 'direct',
    user: initialUsers[1],
    views: 41000,
    likes: 3800,
    comments: [],
    destination: destinations[5],
    category: 'City',
    description: 'Walking through history at the Colosseum and Roman Forum in Rome.',
  },
  {
    id: 'v7',
    title: 'Paragliding over Manali',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    thumbnailUrl: placeholderImages.find(p => p.id === 'video-thumb-7')?.imageUrl || '',
    source: 'direct',
    user: initialUsers[0],
    views: 9000,
    likes: 850,
    comments: [],
    destination: destinations[1],
    category: 'Mountain',
    description: 'Soaring through the skies and getting a bird\'s eye view of Manali\'s beauty.',
  },
  {
    id: 'v8',
    title: 'Parisian Street Food',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: placeholderImages.find(p => p.id === 'video-thumb-8')?.imageUrl || '',
    source: 'direct',
    user: initialUsers[1],
    views: 12500,
    likes: 1100,
    comments: [],
    destination: destinations[2],
    category: 'Food',
    description: 'Tasting the delicious crepes and other street food delights in Paris.',
  }
];

export const stories: Story[] = [
    { id: 's1', user: initialUsers[1], imageUrl: 'https://images.unsplash.com/photo-1533106418989-87423dec6928?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw5fHx0cmF2ZWwlJTIwc3Rvcnl8ZW58MHx8fHwxNzY4MTYyMjIyfDA&ixlib=rb-4.1.0&q=80&w=1080' },
    { id: 's2', user: initialUsers[0], imageUrl: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHx0cmF2ZWwlJTIwYmVhY2h8ZW58MHx8fHwxNzY4MTYyMjM4fDA&ixlib=rb-4.1.0&q=80&w=1080', viewed: true },
    { id: 's3', user: initialUsers[2], imageUrl: 'https://images.unsplash.com/photo-1473625247510-8ceb1760943f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHx0cmF2ZWwlJTIwZm9yZXN0fGVufDB8fHx8MTc2ODE2MjI2MHww&ixlib=rb-4.1.0&q=80&w=1080' },
    { id: 's4', user: initialUsers[3], imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxtb3VudGFpbiUyMHRyYXZlbHxlbnwwfHx8fDE3NjgyNDIxODB8MA&ixlib=rb-4.1.0&q=80&w=1080' },
];
