
"use client";

import { useState, useRef, ChangeEvent } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { PageHeader } from '@/components/page-header';
import { Button } from '@/components/ui/button';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Progress } from '@/components/ui/progress';
import { useToast } from '@/hooks/use-toast';
import { CheckCircle, UploadCloud, Youtube, Instagram, Send, Loader2, Sparkles } from 'lucide-react';
import { VideoCategory } from '@/lib/types';
import { ScrollArea, ScrollBar } from '@/components/ui/scroll-area';
import { cn } from '@/lib/utils';
import { Tabs, TabsContent } from '@/components/ui/tabs';
import { useVideoStore } from '@/hooks/use-video-store';
import { autoGenerateDescription } from '@/ai/flows/auto-generate-description';
import { generateVideoTitles } from '@/ai/flows/generate-video-titles';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";


const categories: VideoCategory[] = ["Beach", "Mountain", "City", "Religious", "Food", "Amusement Park", "Forest", "Tropical", "Camping", "Other"];

const formSchema = z.object({
  title: z.string().min(5, "Title must be at least 5 characters."),
  country: z.string().min(2, "Country is required."),
  state: z.string().min(2, "State is required."),
  place: z.string().min(2, "Place is required."),
  category: z.enum(["Beach", "Mountain", "City", "Religious", "Food", "Amusement Park", "Forest", "Tropical", "Camping", "Other"]),
  description: z.string().min(10, "Description must be at least 10 characters.").max(500),
  youtubeUrl: z.string().url("Please enter a valid YouTube URL.").optional().or(z.literal('')),
  instagramUrl: z.string().url("Please enter a valid Instagram URL.").optional().or(z.literal('')),
  telegramUrl: z.string().url("Please enter a valid Telegram URL.").optional().or(z.literal('')),
  videoFile: z.any().optional(),
});

type UploadFormValues = z.infer<typeof formSchema>;

const uploadOptions = [
  { value: 'direct', label: 'Direct Upload', icon: <UploadCloud className="h-5 w-5" /> },
  { value: 'youtube', label: 'YouTube', icon: <Youtube className="h-5 w-5" /> },
  { value: 'instagram', label: 'Instagram', icon: <Instagram className="h-5 w-5" /> },
  { value: 'telegram', label: 'Telegram', icon: <Send className="h-5 w-5" /> },
]

export default function UploadPage() {
  const { toast } = useToast();
  const [uploadProgress, setUploadProgress] = useState(0);
  const [isUploading, setIsUploading] = useState(false);
  const [uploadComplete, setUploadComplete] = useState(false);
  const [uploadType, setUploadType] = useState("direct");
  const [fileName, setFileName] = useState('');
  const [isGeneratingDesc, setIsGeneratingDesc] = useState(false);
  const [isGeneratingTitles, setIsGeneratingTitles] = useState(false);
  const [showTitleSuggestions, setShowTitleSuggestions] = useState(false);
  const [suggestedTitles, setSuggestedTitles] = useState<string[]>([]);
  const videoFileRef = useRef<File | null>(null);

  const { addVideo } = useVideoStore();

  const form = useForm<UploadFormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      title: "",
      country: "",
      state: "",
      place: "",
      category: "Other",
      description: "",
      youtubeUrl: "",
      instagramUrl: "",
      telegramUrl: "",
    },
  });

  const handleFileChange = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      form.setValue('videoFile', file);
      setFileName(file.name);
      videoFileRef.current = file;
    }
  };

  const handleGenerateDescription = async () => {
    if (!videoFileRef.current) {
        toast({
            variant: "destructive",
            title: "No video selected",
            description: "Please upload a video to generate a description.",
        });
        return;
    }
    
    setIsGeneratingDesc(true);
    
    try {
        const reader = new FileReader();
        reader.readAsDataURL(videoFileRef.current);
        reader.onload = async () => {
            const videoDataUri = reader.result as string;
            try {
                const result = await autoGenerateDescription({ videoDataUri });
                form.setValue('description', result.description);
                toast({
                    title: "Description generated!",
                    description: "The AI has generated a description for your video.",
                });
            } catch (error) {
                console.error("Error generating description: ", error);
                toast({
                    variant: "destructive",
                    title: "Generation failed",
                    description: "Could not generate a description for the video.",
                });
            } finally {
                setIsGeneratingDesc(false);
            }
        };
        reader.onerror = (error) => {
            console.error("File reading error: ", error);
            toast({
                variant: "destructive",
                title: "File read error",
                description: "Could not read the selected video file.",
            });
            setIsGeneratingDesc(false);
        };

    } catch (e) {
      console.error(e);
      toast({
        variant: "destructive",
        title: "Uh oh! Something went wrong.",
        description: "Could not generate description.",
      });
      setIsGeneratingDesc(false);
    }
  };

    const handleGenerateTitles = async () => {
    const description = form.getValues('description');
    if (!description || description.length < 10) {
      toast({
        variant: 'destructive',
        title: 'Description too short',
        description:
          'Please write a description of at least 10 characters before generating titles.',
      });
      return;
    }
    setIsGeneratingTitles(true);
    try {
      const result = await generateVideoTitles({ description });
      setSuggestedTitles(result.suggestedTitles);
      setShowTitleSuggestions(true);
    } catch (error) {
      console.error('Error generating titles:', error);
      toast({
        variant: 'destructive',
        title: 'Title generation failed',
        description: 'Could not generate titles for the video.',
      });
    } finally {
      setIsGeneratingTitles(false);
    }
  };

  const selectTitle = (title: string) => {
    form.setValue('title', title);
    setShowTitleSuggestions(false);
  };


  const onSubmit = (data: UploadFormValues) => {
    let sourceUrl = '';
    let sourceType: 'direct' | 'youtube' | 'instagram' | 'telegram' = 'direct';

    if (uploadType === 'direct') {
        if (!data.videoFile) {
            form.setError('videoFile', { message: 'Please select a video file to upload.' });
            return;
        }
        sourceUrl = URL.createObjectURL(data.videoFile);
        sourceType = 'direct';
    }
    if (uploadType === 'youtube') {
        if (!data.youtubeUrl) {
            form.setError('youtubeUrl', { message: 'Please paste a YouTube URL.' });
            return;
        }
        sourceUrl = data.youtubeUrl;
        sourceType = 'youtube';
    }
    if (uploadType === 'instagram') {
        if (!data.instagramUrl) {
            form.setError('instagramUrl', { message: 'Please paste an Instagram URL.' });
            return;
        }
        sourceUrl = data.instagramUrl;
        sourceType = 'instagram';
    }
    if (uploadType === 'telegram') {
        if (!data.telegramUrl) {
            form.setError('telegramUrl', { message: 'Please paste a Telegram URL.' });
            return;
        }
        sourceUrl = data.telegramUrl;
        sourceType = 'telegram';
    }
    
    setIsUploading(true);
    setUploadComplete(false);
    setUploadProgress(0);

    const interval = setInterval(() => {
      setUploadProgress((prev) => (prev >= 95 ? prev : prev + 10));
    }, 300);

    setTimeout(() => {
      clearInterval(interval);
      setUploadProgress(100);
      setTimeout(() => {
        addVideo({
            ...data,
            source: sourceType,
            videoUrl: sourceUrl
        });

        setIsUploading(false);
        setUploadComplete(true);
        toast({
          title: "Upload Successful!",
          description: "Your video has been submitted for processing.",
        });
        form.reset();
        setUploadType('direct');
        setFileName('');
        videoFileRef.current = null;
      }, 500);
    }, 3500);
  };

  return (
    <>
      <PageHeader title="Share Experience" />
      <div className="container max-w-2xl py-8">
        <Tabs value={uploadType} onValueChange={setUploadType} className="w-full">
          <div className="pb-4">
            <ScrollArea className="w-full whitespace-nowrap">
              <div className="flex w-max space-x-2 pb-2">
                {uploadOptions.map((option) => (
                   <button
                    key={option.value}
                    onClick={() => setUploadType(option.value)}
                    className={cn(
                      "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-full text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 px-4 py-2",
                      uploadType === option.value
                        ? "bg-primary text-primary-foreground shadow-sm"
                        : "bg-card text-card-foreground border hover:bg-accent/50"
                    )}
                  >
                    {option.icon}
                    {option.label}
                  </button>
                ))}
              </div>
              <ScrollBar orientation="horizontal" />
            </ScrollArea>
          </div>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-8 mt-6">
              <TabsContent value="direct" className="m-0">
                <FormField
                  control={form.control}
                  name="videoFile"
                  render={() => (
                    <FormItem>
                      <FormLabel>Video File</FormLabel>
                      <FormControl>
                        <div className="flex items-center justify-center w-full">
                          <label htmlFor="dropzone-file" className="flex flex-col items-center justify-center w-full h-48 border-2 border-dashed rounded-lg cursor-pointer bg-card hover:bg-accent/50">
                            <div className="flex flex-col items-center justify-center pt-5 pb-6">
                              <UploadCloud className="w-10 h-10 mb-3 text-muted-foreground" />
                              {fileName ? (
                                <p className="font-semibold text-primary">{fileName}</p>
                              ) : (
                                <>
                                <p className="mb-2 text-sm text-muted-foreground"><span className="font-semibold">Click to upload</span> or drag and drop</p>
                                <p className="text-xs text-muted-foreground">MP4, MOV, AVI (MAX. 500MB)</p>
                                </>
                              )}
                            </div>
                            <Input id="dropzone-file" type="file" className="hidden" accept="video/*" onChange={handleFileChange} />
                          </label>
                        </div>
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </TabsContent>
              <TabsContent value="youtube" className="m-0">
                <FormField
                  control={form.control}
                  name="youtubeUrl"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>YouTube Video URL</FormLabel>
                      <FormControl>
                        <Input placeholder="https://www.youtube.com/watch?v=..." {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </TabsContent>
              <TabsContent value="instagram" className="m-0">
                <FormField
                  control={form.control}
                  name="instagramUrl"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Instagram Video URL</FormLabel>
                      <FormControl>
                        <Input placeholder="https://www.instagram.com/reel/..." {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </TabsContent>
              <TabsContent value="telegram" className="m-0">
                <FormField
                  control={form.control}
                  name="telegramUrl"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Telegram Video URL</FormLabel>
                      <FormControl>
                        <Input placeholder="https.t.me/channel/..." {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </TabsContent>

              <FormField
                control={form.control}
                name="title"
                render={({ field }) => (
                  <FormItem>
                    <div className="flex justify-between items-center">
                        <FormLabel>Video Title</FormLabel>
                         <Button
                            type="button"
                            onClick={handleGenerateTitles}
                            variant="link"
                            size="sm"
                            disabled={isGeneratingTitles}
                            className="text-primary disabled:text-muted-foreground"
                        >
                            {isGeneratingTitles ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Generating...</> : <>Suggest Titles <Sparkles className="ml-2 h-4 w-4" /></>}
                        </Button>
                    </div>
                    <FormControl>
                      <Input placeholder="e.g., My amazing trip to the mountains" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <FormField
                  control={form.control}
                  name="country"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Country</FormLabel>
                      <FormControl>
                        <Input placeholder="e.g., India" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="state"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>State</FormLabel>
                      <FormControl>
                        <Input placeholder="e.g., Himachal Pradesh" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="place"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Place</FormLabel>
                      <FormControl>
                        <Input placeholder="e.g., Manali" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              <FormField
                control={form.control}
                name="category"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Category</FormLabel>
                    <Select onValueChange={field.onChange} defaultValue={field.value}>
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Select a category" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {categories.map(category => (
                           <SelectItem key={category} value={category}>{category}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="description"
                render={({ field }) => (
                  <FormItem>
                    <div className="flex justify-between items-center">
                        <FormLabel>Description</FormLabel>
                        <Button
                            type="button"
                            onClick={handleGenerateDescription}
                            variant="link"
                            size="sm"
                            disabled={isGeneratingDesc || uploadType !== 'direct'}
                            className="text-primary disabled:text-muted-foreground"
                        >
                            {isGeneratingDesc ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Generating...</> : <>Auto-generate with AI <Sparkles className="ml-2 h-4 w-4" /></>}
                        </Button>
                    </div>
                    <FormControl>
                      <Textarea placeholder="Tell us more about your video..." className="resize-none" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              {isUploading && (
                <div className="space-y-2">
                    <p className="text-sm font-medium">Uploading...</p>
                    <Progress value={uploadProgress} />
                </div>
              )}

              {uploadComplete && (
                <div className="flex items-center p-4 text-sm text-green-800 rounded-lg bg-green-100 dark:bg-gray-800 dark:text-green-400" role="alert">
                    <CheckCircle className="flex-shrink-0 inline w-4 h-4 mr-3"/>
                    <span className="font-medium">Upload complete!</span> Your video is now being processed.
                </div>
              )}

              <Button type="submit" className="w-full" disabled={isUploading || isGeneratingDesc || isGeneratingTitles}>
                {isUploading ? "Uploading..." : "Share Experience"}
              </Button>
            </form>
          </Form>
        </Tabs>
      </div>
      <Dialog open={showTitleSuggestions} onOpenChange={setShowTitleSuggestions}>
        <DialogContent>
            <DialogHeader>
            <DialogTitle>Suggested Titles</DialogTitle>
            <DialogDescription>
                Here are some AI-generated titles for your video. Click one to use it.
            </DialogDescription>
            </DialogHeader>
            <div className="flex flex-col gap-2">
                {suggestedTitles.map((title, index) => (
                    <Button key={index} variant="outline" onClick={() => selectTitle(title)}>
                        {title}
                    </Button>
                ))}
            </div>
            <DialogFooter>
                <Button variant="ghost" onClick={() => setShowTitleSuggestions(false)}>Close</Button>
            </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );

    